### ISSUE TITLE
[FEATURE REQUEST] add an additional overlay in the events section of the UI

### ISSUE THREAD

**Issue by xinity** [Issif/falcosidekick-ui#96]
**Motivation**

if we want to have a detailed view of en event, in the "events" section we need to scroll horizontally which is not great for UX

**Feature**

is there any way to add an clickable overlay so when click on a events we can have the details of it without having to scroll ?

**Alternatives**
so far none

**Additional context**

so far none

**Comment by Issif** [comment]
#106
